import type { ContentItem, WorkshopItem, ServiceItem, ProjectItem } from '../types';

export const INITIAL_WORKSHOPS: WorkshopItem[] = [
  {
    id: 'ws-001',
    code: '001',
    title: 'CONSTRUCCIÓN DE PEDAL FUZZ GERMANIO DIY',
    slug: 'construccion-pedal-fuzz-germanio',
    summary: 'Aprende a soldar, entender el circuito Fuzz Face clásico, emparejar transistores de germanio y construir tu propio pedal desde cero.',
    description: 'Taller intensivo presencial de 6 horas donde aprenderás los fundamentos de la electrónica analógica para audio. Ensamblaremos un circuito Fuzz vintage punto a punto en PCB reforzada, seleccionando componentes NOS (New Old Stock), calibrando el bias de transistores y perforando el gabinete de aluminio Hammond 1590B.',
    category: 'educativa',
    imageUrl: 'https://images.unsplash.com/photo-1675602488453-c3897a475af5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Pedal de guitarra desarmado con componentes electrónicos vintage',
    tags: ['Pedales DIY', 'Fuzz', 'Soldadura', 'Audio Analógico'],
    featured: true,
    published: true,
    durationHours: 6,
    level: 'Principiante',
    materialsIncluded: true,
    spotsLimit: 8,
    price: 65000,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'ws-002',
    code: '002',
    title: 'SINTETIZADOR DE RUIDO & OSCILADORES 40106 CMOS',
    slug: 'sintetizador-ruido-osciladores-cmos',
    summary: 'Crea tu propia máquina de drones y texturas sonoras utilizando compuertas lógicas integradas CD40106 y modulación cruzada.',
    description: 'En este taller exploramos la síntesis analógica experimental basada en chips CMOS. Construirás un generador de 6 osciladores de onda cuadrada con potenciómetros de frecuencia, control de starvación de voltaje (power sag) y salida jack 1/4" lista para conectar a amplificadores o pedales de delay.',
    category: 'educativa',
    imageUrl: 'https://images.unsplash.com/photo-1776244957061-7278ce18bf34?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Circuito integrado y cables sobre protoboard con luces led',
    tags: ['Sintetizadores', 'CMOS', 'Noise Machine', 'Electrónica Creativa'],
    featured: true,
    published: true,
    durationHours: 5,
    level: 'Intermedio',
    materialsIncluded: true,
    spotsLimit: 10,
    price: 55000,
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 'ws-003',
    code: '003',
    title: 'FUNDAMENTOS DE DIAGNÓSTICO Y SOLDADURA AUDIÓFILA',
    slug: 'fundamentos-diagnostico-soldadura',
    summary: 'Manejo de multímetro, osciloscopio básico, técnicas de desoldado con bomba/malla y detección de fallas en cables y conectores.',
    description: 'La base fundamental que todo músico y entusiasta necesita para no depender de terceros en emergencias técnicas. Aprende a estañar correctamente cables de audio Mogami/Neutrik, cambiar potenciómetros scratchy, revisar pistas de masa rotas y comprobar componentes pasivos con tester digital.',
    category: 'educativa',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1663040598592-9f3e311f9841?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Estación de soldadura y estaño sobre banco de trabajo',
    tags: ['Mantenimiento', 'Soldadura', 'Cables', 'Herramientas'],
    featured: false,
    published: true,
    durationHours: 4,
    level: 'Principiante',
    materialsIncluded: true,
    spotsLimit: 12,
    price: 40000,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-001',
    code: '004',
    title: 'REPARACIÓN & CALIBRACIÓN DE PEDALES DE EFECTOS',
    slug: 'reparacion-calibracion-pedales',
    summary: 'Diagnóstico profundo de ruido, cambio de footswitch 3PDT true-bypass, jacks neutrik, potenciómetros y recambio de condensadores secos.',
    description: 'Servicio técnico especializado para pedales analógicos y digitales clásicos (Boss, Electro-Harmonix, Ibanez, Dunlop, MXR, boutique). Solucionamos ruidos parásitos, cortes de señal, sustitución de switches defectuosos por switches de alta durabilidad y adaptaciones a alimentación 9V centro negativo estándar.',
    category: 'servicios',
    imageUrl: 'https://images.unsplash.com/photo-1634246370421-15d6d198c4ab?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Pedales de efectos de guitarra abiertos en taller de reparación',
    tags: ['Reparación', 'True Bypass', 'Calibración', 'Pedalboard'],
    featured: true,
    published: true,
    serviceType: 'Reparación',
    estimatedTurnaround: '3 a 5 días hábiles',
    startingPrice: 25000,
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'srv-002',
    code: '005',
    title: 'MODIFICACIONES DE CIRCUITO & UPGRADES AUDIÓFILOS',
    slug: 'modificaciones-circuito-upgrades',
    summary: 'Mods clásicos: Keeley/Monte Allums para Boss SD-1/DS-1, clipping switches de diodos asimétricos, loops de efectos y mejoras de rango dinámico.',
    description: 'Lleva tus pedales comerciales al siguiente nivel sonoro. Reemplazamos amplificadores operacionales estándar por chips low-noise (TL072, OPA2134), instalamos selectores para conmutar entre diodos de silicio, germanio o LED clipping, y ampliamos la respuesta de graves para bajo o guitarras con afinaciones bajas.',
    category: 'servicios',
    imageUrl: 'https://images.unsplash.com/photo-1751887687425-64b20d82f344?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Circuito impreso con diodos y condensadores modificados',
    tags: ['Mods', 'Clipping Mod', 'Low Noise', 'Custom Tone'],
    featured: true,
    published: true,
    serviceType: 'Modificación',
    estimatedTurnaround: '5 a 7 días hábiles',
    startingPrice: 35000,
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'srv-003',
    code: '006',
    title: 'MANTENIMIENTO DE AMPLIFICADORES A TUBOS Y ESTADO SÓLIDO',
    slug: 'mantenimiento-amplificadores-tubos',
    summary: 'Revalvulaje, ajuste de Bias con zócalos de medición, recaping de electrolíticos de alta tensión y limpieza ultrasónica de contactos.',
    description: 'Cuidado profesional para amplificadores de guitarra y bajo valvulares y transistorizados. Medición segura de voltajes B+, diagnóstico de zumbido de 50/60Hz, balanceo de etapas de potencia con pares matcheados y reemplazo seguro de filtros envejecidos.',
    category: 'servicios',
    imageUrl: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAlt: 'Válvulas de vacío encendidas en amplificador de audio',
    tags: ['Tubos', 'Amplificadores', 'Bias Check', 'Recaping'],
    featured: false,
    published: true,
    serviceType: 'Reparación',
    estimatedTurnaround: '7 a 10 días hábiles',
    startingPrice: 45000,
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
  },
];

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: 'prj-001',
    code: '007',
    title: 'VGA CONVERTER FEEDBACK GENERATOR & GLITCH CORE',
    slug: 'vga-converter-feedback-generator',
    summary: 'Hackeo de escalador de video VGA a Compuesto creando bucles de retroalimentación hipnóticos de distorsión analógica de video.',
    description: 'Inspirado en la cultura lo-fi de sintetizadores de video analógico de los años 90. Modificamos un convertidor de video económico interceptando las líneas de sincronismo vertical/horizontal e inyectando señales de audio directo para que la música dibuje patrones abstractos en monitores CRT.',
    category: 'cosas-interesantes',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Patrón de distorsión y glitch analógico de video multicolor',
    tags: ['Video Synth', 'CRT Glitch', 'Circuit Bending', 'Lo-Fi Video'],
    featured: true,
    published: true,
    projectType: 'Video Synth',
    schematicUrl: 'https://github.com',
    demoVideoUrl: 'https://youtube.com',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'prj-002',
    code: '008',
    title: 'CASSETTE TAPE DELAY MELLOTRON HACK',
    slug: 'cassette-tape-delay-mellotron',
    summary: 'Grabadora de cassette portátil modificada con control de velocidad por voltaje (VCO) y cinta en bucle magnético infinito.',
    description: 'Transformación de un Walkman clásico en un instrumento musical. Reemplazamos el circuito regulador de velocidad de motor por un control analógico por potenciómetro y fotocelda óptica sensible a la luz ambiental, logrando efectos de wow, flutter y tape saturation vintage.',
    category: 'cosas-interesantes',
    imageUrl: '',
    imageAlt: 'Cinta de cassette vintage con bobinas abiertas y circuito expuesto',
    tags: ['Tape Loop', 'Analog Hack', 'Tape Delay', 'Lo-Fi Audio'],
    featured: true,
    published: true,
    projectType: 'Audio Hack',
    schematicUrl: 'https://github.com',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'prj-003',
    code: '009',
    title: 'OPTO-TREMOLO CON BOMBILLA NEÓN Y FOTORRESISTENCIA LDR',
    slug: 'opto-tremolo-neon-ldr',
    summary: 'Oscilador óptico de baja frecuencia (LFO) totalmente analógico sin microcontroladores para un sonido trémolo vintage de los 60s.',
    description: 'Un homenaje a los circuitos de amplificadores Fender Blackface. El corazón del pedal es un optoacoplador artesanal sellado en termoencogible que modula la amplitud de la señal de guitarra de forma suave y cálida con oscilador de relajación a transistor unijuntura.',
    category: 'cosas-interesantes',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Componentes ópticos y leds brillando en placa de circuito',
    tags: ['Opto Tremolo', 'Vintage Circuit', 'DIY Pedal', 'LFO'],
    featured: false,
    published: true,
    projectType: 'Pedal DIY',
    schematicUrl: 'https://github.com',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-25T10:00:00Z',
  },
];

export const INITIAL_CONTENT_ITEMS: ContentItem[] = [
  ...INITIAL_WORKSHOPS,
  ...INITIAL_SERVICES,
  ...INITIAL_PROJECTS,
];
